### ISSUE TITLE
Prevent empty git pushes by checking if there are commits not yet pushed to the remote (LMBQ-156)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/Git-hg-Mirror-Daemon#2]
Using the [`git log` command](https://git-scm.com/docs/git-log#_examples). For example, in the [`Save-AzureWebAppSqlDatabaseToRepository` cmdlet in Infrastructure Scripts](https://github.com/Lombiq/Infrastructure-Scripts/blob/a59e60729d4b7331d1dea36ea7f0adc533970f09/PowerShell/Azure/Sql/Save-AzureWebAppSqlDatabaseToRepository/Save-AzureWebAppSqlDatabaseToRepository.psm1#L133) we use it to determine whether pushing the files to the repository was successful.

Given:
1. A repository with one branch (main) and two origins (alpha and beta).
2. With alpha being one commit ahead of beta.
3. Local main branch being in sync with origin alpha.
4. The `git log --branches --not --remotes=beta` command outputs the following:
```
commit f99f898f93ad3ca4cf584c133772bd5509982372 (HEAD -> main, alpha/main)
Author: ...
Date:   Tue Apr 4 09:28:47 2023 +0200

    Test commit message
```

Supposedly works for any number of branches, so processing the output would tell us if there were commits to sync and exactly which branches need to be pushed (also have to consider the `ref` filter - or is that already taken into account when cloning?). The latter might not matter for mirror-push, but it's worth checking if selectively pushing the branches is faster (and/or better for GitHub).

[Jira issue](https://lombiq.atlassian.net/browse/LMBQ-156)

**Comment by Piedone** [comment]
This needs a remote command for every sync then as well, right? So, instead of blindly pushing, we need a `git log` before conditionally pushing. Because then we use the remote infra similarly than today.

The ref filter is only for pushing currently.

**Comment by BenedekFarkas** [comment]
> This needs a remote command for every sync then as well, right? So, instead of blindly pushing, we need a git log before conditionally pushing. Because then we use the remote infra similarly than today.

If you mean remote command by something that needs to reach out to the remote repository where we'd push changes, then yes. 
In case of a git-git sync, the whole process can be done with git commands only, but we still need to fetch from both remotes and then use `git log` to check which branches have commits that haven't been pushed to the target origin. But a fetch might be less of a problem for GitHub than an empty push (they should confirm).

And/or introduce a minimum frequency, because now it works like old DOS games on modern hardware: if there's a lot to do, then it slows down (= lot of repos cause a larger delay between pushes for a given repository) and vice versa. Basically, a boost button. :)

**Comment by Piedone** [comment]
Yeah, a fetch might be better, thanks.

**Comment by Piedone** [comment]
Suggestions from the GitHub team:

### 1. Using `git push` still, but avoiding empty pushes

> We would like to avoid the empty push scenarios. Can you avoid the empty pushes by relying on Git's reference checks? Also what options are you passing to the git push command such that you are always pushing the empty pushes when there are no changes?
Git itself realizes when a reference is up to date and doesn't try to actually do a push. Typically, a Git push consists of a query of the references and then, if necessary, the sending of a packfile and ref update. If the reference is already at the desired point, then there's nothing to do, and Git says “Everything up-to-date”. You can see this yourself with `GIT_TRACE=1 GIT_TRACE_PACKET=1 git push origin HEAD` if you do it twice in a row. )

We're using [LibGit2Sharp](https://github.com/libgit2/libgit2sharp) to interact with Git. Perhaps, unlike the Git CLI, it always needs to do a full push, even if it'll be empty in the end. In the version we use, this seems to be given, but perhaps updating it to the latest version would simply fix this?

### 2. Lower sync rate

We'd need to add an explicit timer instead of the current loop, to have something like a mirroring operation every 10 minutes.

### 3. Using the GitHub API

> Alternatively, would you consider doing something for GitHub repos where you took advantage of webhooks or events to trigger the repo sync, instead of doing Git pulls/pushes?
Could you install a [webhook to be notified](https://docs.github.com/en/webhooks-and-events/webhooks/about-webhooks) and not poll?
If you don't own the repo in question, another option for finding out about pushes to public repos that would not require the ability to install a webhook is the [events](https://docs.github.com/en/rest/activity/events?apiVersion=2022-11-28) API. That is subject to a 5 minute delay and "optimized for polling with the ETag header" and rate limiting would apply, so you'd need to respect the X-Poll-Interval header.

This I'd rather avoid. Apart from being quite a substantial change to how GHM works, it'd also exclude other Git hosting providers, or we'd need to maintain something just for GitHub.

### All in all

I'd try the following:

1. The Git CLI doesn't do an empty push in the scenario where the remote is already up to date. Check if we achieve this with LibGit2Sharp. If not:
2. Do what Benedek explains above. We already do a Git clone or fetch before pushing to the target repo, so we could similarly do a fetch from the target repo and check whether a push needs to be done at all locally.

Additionally, implement a 10-minute sync rate.

**Comment by BenedekFarkas** [comment]
> The Git CLI doesn't do an empty push in the scenario where the remote is already up to date. Check if we achieve this with LibGit2Sharp.

Didn't find anything explicit about this, but with a brief search found this commit that might provide the extension point we need to handle this: https://github.com/libgit2/libgit2sharp/commit/ab895be9bd4dc3099f84154156fa2195675ea08f
